### ISSUE TITLE
Back ?

### ISSUE THREAD

**Issue by hackmann32** [sebinside/StreamAwesome#1]
ist das normal
![Screenshot 2022-01-31 023141](https://user-images.githubusercontent.com/32334803/151727397-4cfb1be7-036e-425f-ac0a-e42e7b0238ef.jpg)
kleiner Tipp ich kann nur Deutsch schreiben deswegen bitte Deutsch zurück Antworten

**Comment by sebinside** [comment]
Du musst die Font Awesome Schriftarten deinem Projekt hinzufügen oder lokal installieren. Ich erstelle demnächst noch eine detaillierte Installationsanleitung.

**Comment by hackmann32** [comment]
danke für die Info aber ich weiß immer noch nicht wie man das installiert und es gibt kein richtiges Fußball Symbol ☹️

**Comment by MelanX** [comment]
> Du musst die Font Awesome Schriftarten deinem Projekt hinzufügen oder lokal installieren. Ich erstelle demnächst noch eine detaillierte Installationsanleitung.

Bin gespannt!

**Comment by sebinside** [comment]
Kommt noch, in 2020 + n, mit n größer gleich 3
