### ISSUE TITLE
No template Folder

### ISSUE THREAD

**Issue by NeoCortex97** [sebinside/StreamAwesome#101]
The repository does not contain any template folder. please add it, or state the path pls :-D

**Comment by Logianer** [comment]
Please explain the issue. What's a template folder? What is it used for?

**Comment by NeoCortex97** [comment]
The instructions state that one should unpack the font-awesome archive to the template directory and rename it afterwards, but the repository does not contain an template directory on main branch.

And I realized that I'm dumb. The directory is supposed to be called prototype.

**Comment by NeoCortex97** [comment]
Fixed by latest commit.

**Comment by NeoCortex97** [comment]
This is no longer valid
