### ISSUE TITLE
Add simpler color selector

### ISSUE THREAD

**Issue by sebinside** [sebinside/StreamAwesome#138]
Add an optional even simpler hue-based color selector, i.e., something like ten base colors to choose from.

**Comment by thowicom** [comment]
You could additional add an option for entering a color code (for example HEX) after clicking on a cogwheel or a pen. Reason: If I'm using an previously generated icon already and I want to generate a new icon with exactly the same color like the old one, I could pick the color from my old icon and paste it into your tool for the new one.
