### ISSUE TITLE
Can't find .css files with Font Awesome 6 Free

### ISSUE THREAD

**Issue by DerArkeN** [sebinside/StreamAwesome#207]
Error message:
![image](https://github.com/sebinside/StreamAwesome/assets/31077445/cfdaa204-a2ce-4912-91bb-b4994444b1d1)
> [vite] Internal server error: Failed to resolve import "../fonts/fontawesome/css/sharp-light.min.css" from "src/main.ts". Does the file exist?
---
My guess is that the free version of Font Awesome doesn't provide the necessary files, which causes the import to fail and the app to crash.

Reproduce:
1. Delete the `fonts/fontawesome` folder
2. Download font awesome free for web [Download](https://fontawesome.com/download)
3. Paste in the folders as stated in the README
4. `npm run dev`

**Comment by MichaHuhn** [comment]
You can temporarly remove the import lines which are causing this error.
Some icons won't load, but the app works again.

**Comment by DerArkeN** [comment]
#208 can fix this
